"""esquema inicial de la capa de datos

Línea de base con las tablas declaradas de forma explícita (autogenerada). No crea las tablas a partir de los
modelos vigentes: esos cambian cada vez que se editan, y la migración siguiente fallaría al intentar crear de
nuevo lo que la base ya trae. Los cambios de esquema van en migraciones nuevas (`alembic revision --autogenerate`).

Revision ID: 0001
Revises: 
Create Date: 2026-09-26 23:32:33.630044
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clasificacion',
    sa.Column('codigo', sa.String(length=5), nullable=False),
    sa.Column('criterio', sa.String(length=15), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('departamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('nombre_normalizado', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre'),
    sa.UniqueConstraint('nombre_normalizado')
    )
    op.create_table('organizacion',
    sa.Column('cuit', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=300), nullable=False),
    sa.Column('tipo', sa.String(length=100), nullable=True),
    sa.Column('tipo_gestora', sa.String(length=30), nullable=True),
    sa.Column('dom_legal', sa.String(length=300), nullable=True),
    sa.Column('contacto', sa.String(length=100), nullable=True),
    sa.Column('cpe', sa.String(length=50), nullable=True),
    sa.Column('presidente', sa.String(length=200), nullable=True),
    sa.Column('dni_presidente', sa.String(length=15), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('nombre_normalizado', sa.String(length=300), nullable=True),
    sa.Column('cuit_provisional', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('cuit')
    )
    with op.batch_alter_table('organizacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizacion_nombre_normalizado'), ['nombre_normalizado'], unique=False)

    op.create_table('rubro_obra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('peso_pct', sa.Integer(), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tecnico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('departamentos', sa.String(length=500), nullable=True),
    sa.Column('activo', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tipo_reporte',
    sa.Column('codigo', sa.String(length=60), nullable=False),
    sa.Column('sistema_origen', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('unidad', sa.String(length=20), nullable=False),
    sa.Column('que_mide', sa.Text(), nullable=False),
    sa.Column('que_no_mide', sa.Text(), nullable=False),
    sa.Column('limites', sa.JSON(), nullable=False),
    sa.Column('confianza', sa.String(length=20), nullable=False),
    sa.Column('revisado_en', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('familia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('representante', sa.String(length=200), nullable=True),
    sa.Column('cuit_org', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['cuit_org'], ['organizacion.cuit'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tipo_reporte', sa.String(length=60), nullable=True),
    sa.Column('archivo_nombre', sa.String(length=300), nullable=False),
    sa.Column('archivo_huella', sa.String(length=64), nullable=False),
    sa.Column('fecha_reporte', sa.Date(), nullable=True),
    sa.Column('parametros', sa.JSON(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('validacion', sa.JSON(), nullable=True),
    sa.Column('filas_leidas', sa.Integer(), nullable=True),
    sa.Column('version_importador', sa.String(length=20), nullable=True),
    sa.Column('importado_en', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tipo_reporte'], ['tipo_reporte.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('importacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_importacion_archivo_huella'), ['archivo_huella'], unique=False)

    op.create_table('organizacion_alias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alias', sa.String(length=300), nullable=False),
    sa.Column('alias_normalizado', sa.String(length=300), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=False),
    sa.Column('origen', sa.String(length=60), nullable=True),
    sa.Column('pendiente_revision', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cuit'], ['organizacion.cuit'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_normalizado')
    )
    op.create_table('integrante_familia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dni', sa.String(length=15), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('apellido', sa.String(length=100), nullable=True),
    sa.Column('condicion_especial', sa.String(length=200), nullable=True),
    sa.Column('id_familia', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_familia'], ['familia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medida_organizacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('importacion_id', sa.Integer(), nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=False),
    sa.Column('consulta', sa.String(length=20), nullable=False),
    sa.Column('metrica', sa.String(length=30), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('periodo_desde', sa.Date(), nullable=True),
    sa.Column('periodo_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['cuit'], ['organizacion.cuit'], ),
    sa.ForeignKeyConstraint(['importacion_id'], ['importacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medida_organizacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medida_organizacion_cuit'), ['cuit'], unique=False)
        batch_op.create_index(batch_op.f('ix_medida_organizacion_importacion_id'), ['importacion_id'], unique=False)

    op.create_table('registro_crudo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('importacion_id', sa.Integer(), nullable=False),
    sa.Column('fila_numero', sa.Integer(), nullable=False),
    sa.Column('datos', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['importacion_id'], ['importacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('registro_crudo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registro_crudo_importacion_id'), ['importacion_id'], unique=False)

    op.create_table('vivienda',
    sa.Column('num_exp', sa.String(length=50), nullable=False),
    sa.Column('departamento', sa.String(length=100), nullable=False),
    sa.Column('localidad', sa.String(length=100), nullable=True),
    sa.Column('barrio', sa.String(length=100), nullable=True),
    sa.Column('direccion', sa.String(length=200), nullable=True),
    sa.Column('superficie', sa.Float(), nullable=True),
    sa.Column('fecha_inic', sa.String(length=10), nullable=True),
    sa.Column('fecha_fin', sa.String(length=10), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('avance_obra', sa.Integer(), nullable=True),
    sa.Column('clasificacion', sa.String(length=10), nullable=True),
    sa.Column('criterio', sa.String(length=15), nullable=True),
    sa.Column('tipo_vivienda', sa.String(length=20), nullable=True),
    sa.Column('cant_dormitorios', sa.Integer(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('id_familia', sa.Integer(), nullable=True),
    sa.Column('representante', sa.String(length=200), nullable=True),
    sa.Column('cuit_org', sa.String(length=20), nullable=True),
    sa.Column('expediente', sa.String(length=50), nullable=True),
    sa.Column('fecha_solicitud', sa.Date(), nullable=True),
    sa.Column('titular_seudonimo', sa.String(length=150), nullable=True),
    sa.Column('nivel_riesgo', sa.String(length=10), nullable=True),
    sa.Column('cluster', sa.Integer(), nullable=True),
    sa.Column('dias_activa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuit_org'], ['organizacion.cuit'], ),
    sa.ForeignKeyConstraint(['id_familia'], ['familia.id'], ),
    sa.PrimaryKeyConstraint('num_exp')
    )
    with op.batch_alter_table('vivienda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vivienda_expediente'), ['expediente'], unique=False)

    op.create_table('asignacion_tecnico',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('vivienda_id', sa.String(length=50), nullable=False),
    sa.Column('fecha_asignacion', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnico.id'], ),
    sa.ForeignKeyConstraint(['vivienda_id'], ['vivienda.num_exp'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avance_obra',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vivienda_id', sa.String(length=50), nullable=False),
    sa.Column('cuit_org', sa.String(length=20), nullable=True),
    sa.Column('fecha', sa.String(length=10), nullable=True),
    sa.Column('etapa', sa.String(length=20), nullable=True),
    sa.Column('porcentaje', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cuit_org'], ['organizacion.cuit'], ),
    sa.ForeignKeyConstraint(['vivienda_id'], ['vivienda.num_exp'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('avance_rubro',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vivienda_id', sa.String(length=50), nullable=False),
    sa.Column('rubro_id', sa.Integer(), nullable=False),
    sa.Column('avance_pct', sa.Integer(), nullable=True),
    sa.Column('fecha_actualizacion', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['rubro_id'], ['rubro_obra.id'], ),
    sa.ForeignKeyConstraint(['vivienda_id'], ['vivienda.num_exp'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visita',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vivienda_id', sa.String(length=50), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('avance_verificado', sa.Integer(), nullable=True),
    sa.Column('estado_relevado', sa.String(length=20), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('diferencia_ong', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnico.id'], ),
    sa.ForeignKeyConstraint(['vivienda_id'], ['vivienda.num_exp'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vivienda_foto',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vivienda_num_exp', sa.String(length=50), nullable=False),
    sa.Column('importacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_reporte', sa.Date(), nullable=True),
    sa.Column('fecha_activacion', sa.Date(), nullable=True),
    sa.Column('avance_obra', sa.Float(), nullable=True),
    sa.Column('fecha_fin_obra', sa.Date(), nullable=True),
    sa.Column('desaprobada', sa.Boolean(), nullable=True),
    sa.Column('exp_reclamo', sa.String(length=200), nullable=True),
    sa.Column('exp_acta', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['importacion_id'], ['importacion.id'], ),
    sa.ForeignKeyConstraint(['vivienda_num_exp'], ['vivienda.num_exp'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vivienda_num_exp', 'importacion_id')
    )
    with op.batch_alter_table('vivienda_foto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vivienda_foto_importacion_id'), ['importacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vivienda_foto_vivienda_num_exp'), ['vivienda_num_exp'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vivienda_foto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vivienda_foto_vivienda_num_exp'))
        batch_op.drop_index(batch_op.f('ix_vivienda_foto_importacion_id'))

    op.drop_table('vivienda_foto')
    op.drop_table('visita')
    op.drop_table('avance_rubro')
    op.drop_table('avance_obra')
    op.drop_table('asignacion_tecnico')
    with op.batch_alter_table('vivienda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vivienda_expediente'))

    op.drop_table('vivienda')
    with op.batch_alter_table('registro_crudo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registro_crudo_importacion_id'))

    op.drop_table('registro_crudo')
    with op.batch_alter_table('medida_organizacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medida_organizacion_importacion_id'))
        batch_op.drop_index(batch_op.f('ix_medida_organizacion_cuit'))

    op.drop_table('medida_organizacion')
    op.drop_table('integrante_familia')
    op.drop_table('organizacion_alias')
    with op.batch_alter_table('importacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_importacion_archivo_huella'))

    op.drop_table('importacion')
    op.drop_table('familia')
    op.drop_table('tipo_reporte')
    op.drop_table('tecnico')
    op.drop_table('rubro_obra')
    with op.batch_alter_table('organizacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizacion_nombre_normalizado'))

    op.drop_table('organizacion')
    op.drop_table('departamento')
    op.drop_table('clasificacion')
    # ### end Alembic commands ###
