"""resto del esquema (Plan 2)

Agrega lo que faltaba de las capas 1 a 4 de la especificación: los catálogos `tipo_solicitante`,
`tipo_vivienda`, `tipo_documento` y `localidad`; las tablas de programa `expediente`, `reclamo` y
`precio_referencia`; la capa 3 (`documento_expediente`, `notificacion`, `historial_cambios`), vacía
hasta que un export traiga esos datos; y la capa 4 restante (`sistema_externo`, `log_sincronizacion`).
También agrega `organizacion.tipo_solicitante`.

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-28 11:15:08.148043
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial_cambios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tabla', sa.String(length=50), nullable=False),
    sa.Column('registro_id', sa.String(length=80), nullable=False),
    sa.Column('campo', sa.String(length=50), nullable=True),
    sa.Column('valor_anterior', sa.Text(), nullable=True),
    sa.Column('valor_nuevo', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sistema_externo',
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('tipo_conexion', sa.String(length=20), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('tipo_documento',
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('tipo_solicitante',
    sa.Column('codigo', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=60), nullable=False),
    sa.Column('grupo', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('tipo_vivienda',
    sa.Column('codigo', sa.String(length=5), nullable=False),
    sa.Column('nombre', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('codigo')
    )
    op.create_table('localidad',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre', 'departamento_id')
    )
    op.create_table('log_sincronizacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sistema_externo', sa.String(length=30), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.Column('resultado', sa.String(length=20), nullable=True),
    sa.Column('detalle', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['sistema_externo'], ['sistema_externo.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('precio_referencia',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('tipo_vivienda', sa.String(length=20), nullable=False),
    sa.Column('dormitorios', sa.Integer(), nullable=True),
    sa.Column('grupo', sa.String(length=10), nullable=True),
    sa.Column('rubro', sa.String(length=30), nullable=True),
    sa.Column('monto', sa.Integer(), nullable=False),
    sa.Column('origen_importacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['origen_importacion_id'], ['importacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expediente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vivienda_num_exp', sa.String(length=50), nullable=False),
    sa.Column('numero', sa.String(length=50), nullable=False),
    sa.Column('formato', sa.String(length=20), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('origen_importacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['origen_importacion_id'], ['importacion.id'], ),
    sa.ForeignKeyConstraint(['vivienda_num_exp'], ['vivienda.num_exp'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vivienda_num_exp', 'numero', 'tipo')
    )
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expediente_vivienda_num_exp'), ['vivienda_num_exp'], unique=False)

    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vivienda_num_exp', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vivienda_num_exp'], ['vivienda.num_exp'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_expediente',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('expediente_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.String(length=30), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['expediente_id'], ['expediente.id'], ),
    sa.ForeignKeyConstraint(['tipo_documento'], ['tipo_documento.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reclamo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cuit', sa.String(length=20), nullable=True),
    sa.Column('expediente_id', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('estado', sa.String(length=30), nullable=True),
    sa.Column('origen_importacion_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cuit'], ['organizacion.cuit'], ),
    sa.ForeignKeyConstraint(['expediente_id'], ['expediente.id'], ),
    sa.ForeignKeyConstraint(['origen_importacion_id'], ['importacion.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_solicitante', sa.String(length=30), nullable=True))
        batch_op.create_foreign_key('fk_organizacion_tipo_solicitante', 'tipo_solicitante',
                                    ['tipo_solicitante'], ['codigo'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizacion', schema=None) as batch_op:
        batch_op.drop_constraint('fk_organizacion_tipo_solicitante', type_='foreignkey')
        batch_op.drop_column('tipo_solicitante')

    op.drop_table('reclamo')
    op.drop_table('documento_expediente')
    op.drop_table('notificacion')
    with op.batch_alter_table('expediente', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expediente_vivienda_num_exp'))

    op.drop_table('expediente')
    op.drop_table('precio_referencia')
    op.drop_table('log_sincronizacion')
    op.drop_table('localidad')
    op.drop_table('tipo_vivienda')
    op.drop_table('tipo_solicitante')
    op.drop_table('tipo_documento')
    op.drop_table('sistema_externo')
    op.drop_table('historial_cambios')
    # ### end Alembic commands ###
