"""medida_categoria (Plan 3)

Agrega `medida_categoria`: los totales por categoría que trae el pie de «Por Solicitante» (antes se
usaban solo para validar y se descartaban). Sirve para armar el indicador «peso de cada tipo de
solicitante» sin depender de asignar `tipo_solicitante` a cada organización, que hoy no tenemos.

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-28 12:58:10.987144
"""
from alembic import op
import sqlalchemy as sa


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('medida_categoria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('importacion_id', sa.Integer(), nullable=False),
    sa.Column('tipo_solicitante', sa.String(length=30), nullable=False),
    sa.Column('consulta', sa.String(length=20), nullable=False),
    sa.Column('metrica', sa.String(length=30), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('periodo_desde', sa.Date(), nullable=True),
    sa.Column('periodo_hasta', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['importacion_id'], ['importacion.id'], ),
    sa.ForeignKeyConstraint(['tipo_solicitante'], ['tipo_solicitante.codigo'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medida_categoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medida_categoria_importacion_id'), ['importacion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medida_categoria_tipo_solicitante'), ['tipo_solicitante'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('medida_categoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medida_categoria_tipo_solicitante'))
        batch_op.drop_index(batch_op.f('ix_medida_categoria_importacion_id'))

    op.drop_table('medida_categoria')
    # ### end Alembic commands ###
